config/routes.rb
Codefoundry::Application.routes.draw do
  
  root :to => 'welcome#index'
  get 'about', :to => 'welcome#about', :as => 'about'
  get 'search', :to => 'welcome#search', :as => 'search'
  get 'faq', :to => 'welcome#faq', :as => 'faq'
  get 'roadmap', :to => 'welcome#roadmap', :as => 'roadmap'

  resource :account

  get 'login', :to => 'user_sessions#new' 
  get 'logout', :to => 'user_sessions#destroy'
  post 'session', :to => 'user_sessions#create'
  get 'signup', :to => 'users#new'

  repository_routes = Proc.new do
    member do
      get :issues # redirects to issue tracker
      get :docs   # redirects to hosted documentation
      get :live   # redirects to live site

      get :commits
      get :revisions

      resources :releases

      post :commit

      get ':tag/changes', :to => 'repositories#changes'

      get ':tag/*path', :to => 'repositories#show'
    end
  end

  resources :users do
    resources( :repositories, &repository_routes )
  end

  resources :users, :as => 'u' do
    resources( :repositories, &repository_routes )
  end

  resources :projects do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :projects, :as => 'p' do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :roles

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @new_projects = Project.newest.limit(5)
    @popular_projects = Project.by_hits.limit(5)
  end

  def about
    render_marker( params[:action] )
  end

  # copy #about for #faq and #roadmap
  alias_method :faq, :about
  alias_method :roadmap, :about
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_context_menu.html.erb
<% unless current_user %>
  <div class="big-button span-7">
    <%= link_to 'Join CodeFoundry', signup_path %>
  </div>
<% end %>

<div class="big-button span-6">
  <%= link_to 'Start a Project', new_project_path %>
</div>

<div class="big-button span-6">
  <%= link_to 'Find a Project', projects_path %>
</div>

<div class="span-6">
  <ul class="horizontal-list">
    <li><%= link_to_unless_current 'About', about_path %></li>
    <li><%= link_to_unless_current 'FAQ', faq_path %></li>
    <li><%= link_to_unless_current 'Roadmap', roadmap_path %></li>
  </ul>
</div>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<p>
  Codefoundry is an open-source code management tool that makes it easy to use
  revision control in your business and other projects.
</p>

<%= start_wide_content %>

<div class="span-11">
<h2>Popular</h2>
<%= render :partial => @popular_projects %>
</div>

<div class="push-2 span-11 last">
<h2>New</h2>
<%= render :partial => @new_projects %>
</div>

<!-- <h2><%= link_to 'Browse projects ->', projects_path %></h2> -->