config/routes.rb
Codefoundry::Application.routes.draw do
  
  root :to => 'welcome#index'
  get 'about', :to => 'welcome#about', :as => 'about'
  get 'search', :to => 'welcome#search', :as => 'search'
  get 'faq', :to => 'welcome#faq', :as => 'faq'
  get 'roadmap', :to => 'welcome#roadmap', :as => 'roadmap'

  resource :account

  get 'login', :to => 'user_sessions#new' 
  get 'logout', :to => 'user_sessions#destroy'
  post 'session', :to => 'user_sessions#create'
  get 'signup', :to => 'users#new'

  repository_routes = Proc.new do
    member do
      get :issues # redirects to issue tracker
      get :docs   # redirects to hosted documentation
      get :live   # redirects to live site

      get :commits
      get :revisions

      resources :releases

      post :commit

      get ':tag/changes', :to => 'repositories#changes'

      get ':tag/*path', :to => 'repositories#show'
    end
  end

  resources :users do
    resources( :repositories, &repository_routes )
  end

  resources :users, :as => 'u' do
    resources( :repositories, &repository_routes )
  end

  resources :projects do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :projects, :as => 'p' do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :roles

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :repositories
  has_many :project_privileges
  has_many :users, :through => :project_privileges
  alias_method :privileges, :project_privileges
  
  default_scope order(:name)
  scope :by_param_scope, lambda { |param| where(:param => param)}
  scope :newest, lambda { with_exclusive_scope {order('created_at DESC')} }
  scope :by_hits, lambda { with_exclusive_scope {order('hits DESC')} }

  validates_presence_of :name
  validates_uniqueness_of :param
  before_save :save_param
  has_attached_file :avatar, :styles => { :thumb => "48x48>" },
    :default_url => "/images/project_:style.png",
    :default_style => :thumb,
    :url => "/projects/:attachment/:id/:style/:filename",
    :path => ":rails_root/public/projects/avatars/:id/:style/:filename"

  cattr_reader :per_page
  @@per_page = 30

  # Hack to make scope always return single item instead of array
  def self.by_param(param)
    by_param_scope(param).first
  end

  # for nice urls
  def to_param
    result = "#{self.name}"
    result.gsub!(/[^\w_ \-]+/i, '') # Remove unwanted chars.
    result.gsub!(/[ \-]+/i, '-') # No more than one of the separator in a row.
    result.gsub!(/^\-|\-$/i, '') # Remove leading/trailing separator.
    result.mb_chars.downcase.to_s
  end

  def save_param
    self.param = to_param
  end
 
  def add_administrator(user)
    r = Role.find_by_name 'Administrator'
    privileges.create!({ :user => user, :role => r })
  end

  # Is this user an editor?
  def editor?(arg)
    privileges.joins(:role).where(:user_id => arg).where(:roles => { :edit_project => true }).first ? true : false
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :update, :edit]
  
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.paginate :page => params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.by_param(params[:id])
    @project.increment!(:hits)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.by_param(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        @project.add_administrator current_user
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.by_param(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.by_param(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def avatar_thumb(avatar)
    image_tag(avatar.url(:thumb), :class => 'double_border', :width => 48, :height => 48)
  end
end

app/views/projects/_context_menu.html.erb
<% if @project and !@project.new_record? %>
<h4>Navigation</h4>
<ul>
    <li><%= link_to 'Project Information', project_path(@project) %></li>
    <li><%= link_to 'Repositories', project_repositories_path(@project) %></li>
</ul>
<% end %>

<h4>Administration</h4>
<ul>
  <% if @project and !@project.new_record? and @project.editor? current_user %>
    <li><%= link_to 'Edit project', edit_project_path(@project) %></li>
  <% end %>
  <li><%= link_to 'New project', new_project_path %></li>
</ul>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => { :multipart => true }) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :summary %><br/>
    <%= f.text_field :summary %><br/>
    <span class="quiet">One-line project description</span>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %><br/> 
    <span class="quiet">Full project description (wiki markup accepted)</span>
  </p>

  <% if !@project.new_record? %>
  <p>
    <p><strong>Current Avatar:</strong><br/>
    <%= avatar_thumb(@project.avatar) %></p>
  </p>
  <% end %>

  <p>
    <%= f.label :avatar, 'Upload an avatar' %><br/>
    <%= f.file_field :avatar %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% if !@project.new_record? %>
<h2>Privileges (<%= link_to 'edit', project_privileges_path(@project) %>)</h2>
<table>
  <tr>
    <th>Username</th>
    <th>Access</th>
    <th></th>
  </tr>

<% @project.privileges.each do |privilege| %>
  <tr>
    <td><%= privilege.user.username %></td>
    <td><%= privilege.role.name %></td>
    <td></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/projects/_project.html.erb
<div class="span-9 last append-bottom">
  <div class="span-2">
    <%= link_to(avatar_thumb(project.avatar), project_path(project)) %>
  </div>

  <div class="span-7 last">
    <strong><%= link_to project.name, project_path(project) %></strong>
    <p><%= project.summary %></p>
  </div>
</div>

<hr style="width: 90%"/>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= render :partial => @projects %>

<%= will_paginate @projects, :class => 'digg_pagination' %>
<br />

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="span-15">
<h1><%= @project.name %></h1>
</div>
<div class="span-3 last">
<%= avatar_thumb @project.avatar %>
</div>
<div class="span-18 last">
<p><%= @project.summary %></p>

<%= marker_to_html(@project.description) %>

</div>