config/routes.rb
Codefoundry::Application.routes.draw do
  
  root :to => 'welcome#index'
  get 'about', :to => 'welcome#about', :as => 'about'
  get 'search', :to => 'welcome#search', :as => 'search'
  get 'faq', :to => 'welcome#faq', :as => 'faq'
  get 'roadmap', :to => 'welcome#roadmap', :as => 'roadmap'

  resource :account

  get 'login', :to => 'user_sessions#new' 
  get 'logout', :to => 'user_sessions#destroy'
  post 'session', :to => 'user_sessions#create'
  get 'signup', :to => 'users#new'

  repository_routes = Proc.new do
    member do
      get :issues # redirects to issue tracker
      get :docs   # redirects to hosted documentation
      get :live   # redirects to live site

      get :commits
      get :revisions

      resources :releases

      post :commit

      get ':tag/changes', :to => 'repositories#changes'

      get ':tag/*path', :to => 'repositories#show'
    end
  end

  resources :users do
    resources( :repositories, &repository_routes )
  end

  resources :users, :as => 'u' do
    resources( :repositories, &repository_routes )
  end

  resources :projects do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :projects, :as => 'p' do
    resources( :repositories, &repository_routes )
    resources( :privileges )
  end

  resources :roles

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= [yield(:title), "Codefoundry"].reject{|item| item.blank? }.join(" - ") %></title>
  <%= stylesheet_link_tag 'application', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'screen', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print', :media => 'print' %>
  <!-- [if lt IE 8]><%= stylesheet_link_tag 'ie', :media => 'screen, projection' %><![endif]-->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <div id="header-container" class="container">
      <div id="notification-area" class="round-bottom push-3 span-18">
        <%= render :partial => 'shared/system_messages', :locals => {:system_message => @system_message} %>
        <%= render :partial => 'shared/flash', :locals => {:flash => flash} %>
        <%= yield :forms %>
      </div>

      <div id="logo" class="span-8">
        <%= link_to root_url do %>
          <span id="code">code</span>foundry
        <% end %>
      </div>

      <div id="login_shortcut" class="push-10 span-6 last">
        <ul class="horizontal-list">
          <% if current_user %>
            <li><%= current_user.username %></li>
            <li><%= link_to 'Account', account_path %></li>
            <li><%= link_to 'Sign out', logout_path %></li>
          <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div id="container-background">
    <div class="container">
      <div id="sidebar" class="span-7 float last">
        <%= yield :pre_sidebar %>
        <%= render 'context_menu' %>
        <%= yield :post_sidebar %>
      </div>

      <div id="content">
        <%= yield %>
      </div>
    </div>

    <div id="footer-background" class="container">
      <div id="footer" class="push-3 span-18">
        <p class="fancy">Enterprise source-code management</p>
        <ul class="small horizontal-list">
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
          <li><%= link_to 'License', 'http://www.gnu.org/licenses/agpl-3.0-standalone.html' %></li>
        </ul>
        <%= svg_tag '3-gears-small.svg', :width => '1em' %>
      </div>
    </div>
  </div>
</body>
</html>